from dotenv import load_dotenv
load_dotenv()

import os
TWITTER_API_KEY = os.getenv('TWITTER_API_KEY')
TWITTER_API_KEY_SECRET = os.getenv('TWITTER_API_KEY_SECRET')
TWITTER_API_BEARER_TOKEN = os.getenv('TWITTER_API_BEARER_TOKEN')

TWITTER_API_ACCESS_TOKEN = os.getenv('TWITTER_API_ACCESS_TOKEN')
TWITTER_API_ACCESS_TOKEN_SECRET = os.getenv('TWITTER_API_ACCESS_TOKEN_SECRET')

TWITTER_API_CLIENT_ID = os.getenv('TWITTER_API_CLIENT_ID')
TWITTER_API_CLIENT_SECRET = os.getenv('TWITTER_API_CLIENT_SECRET')
